version: '3.2'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: number_generator
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - ./app:/app
    command: tail -f /dev/null
    # TODO use .env files for credentials
    environment:
      RABBITMQ_URI: 'amqp://username:password@$rabbitmq'
    networks:
      ninja_shared: { }

networks:
  ninja_shared:
    external: true
