version: '3.2'
services:
  rabbitmq:
    image: rabbitmq:3.13.0-rc.1-management-alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_ERLANG_COOKIE: 'your_secret_cookie'
      RABBITMQ_DEFAULT_USER: 'username'
      RABBITMQ_DEFAULT_PASS: 'password'

    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      ninja_shared: {}

networks:
  ninja_shared:
    external: true
